version: "3"
services:
  db-check:
    container_name: "db-check"
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: ["/bin/bash"]
    volumes:
      - ./:/app